ccre:
  bed_gz: data/{species}/ccre/{ccre_type}.bed.gz
  bed: data/{species}/ccre/{ccre_type}.bed

procap:
  bed_gz: data/human/procap/{pc_biosamp}_{pc_rep}_{pc_output}.bed.gz
  bed: data/human/procap/{pc_biosamp}_{pc_rep}_{pc_output}.bed
  bed_format: data/human/procap/{pc_biosamp}_{pc_rep}_{pc_output}_formatted.bed

lr:
  ca: data/{species}/lr/ca.h5
  meta: data/{species}/lr/metadata.tsv
  encode_meta: data/{species}/lr/encode_metadata.tsv
  filt_ab: data/{species}/lr/filt_ab.tsv

  det_mat: data/{species}/lr/tss_det_matrix.tsv
  bed: data/{species}/lr/{lr_biosamp}_{lr_rep}.bed
  bed_format: data/{species}/lr/{lr_biosamp}_{lr_rep}_formatted.bed
