ref:
  gtf: ref/{species}/annot.gtf

ccre:
  bed_gz: data/{species}/ccre/{ccre_type}.bed.gz
  bed: data/{species}/ccre/{ccre_type}.bed
  bed_format: data/{species}/ccre/{ccre_type}_formatted.bed

  intersect: data/{species}/ccre/intersect/{ccre_type}.bed

procap:
  encode_meta: data/human/procap//encode_metadata.tsv
  bed_gz: data/human/procap/{pc_biosamp}_{pc_rep}_{pc_output}.bed.gz
  bed: data/human/procap/{pc_biosamp}_{pc_rep}_{pc_output}.bed
  bed_format: data/human/procap/{pc_biosamp}_{pc_rep}_{pc_output}_formatted.bed

lr:
  ca: data/{species}/lr/ca.h5
  meta: data/{species}/lr/metadata.tsv
  encode_meta: data/{species}/lr/encode_metadata.tsv
  filt_ab: data/{species}/lr/filt_ab.tsv

  det_mat: data/{species}/lr/tss_det_matrix.tsv
  bed: data/{species}/lr/{lr_biosamp}_{lr_rep}.bed
  bed_format: data/{species}/lr/{lr_biosamp}_{lr_rep}_formatted.bed


chip:
  encode_meta: data/human/{chip_target}_chip/encode_metadata.tsv
  bed_gz: data/human/{chip_target}_chip/{biosamp}_{rep}.bed.gz
  bed: data/human/{chip_target}_chip/{biosamp}_{rep}.bed

# h3k4me3:
#   encode_meta: data/human/h3k4me3_chip/encode_metadata.tsv
#   bed_gz: data/human/h3k4me3_chip/{h3k4me3_biosamp}_{h3k4me3_rep}.bed.gz
#   bed: data/human/h3k4me3_chip/{h3k4me3_biosamp}_{h3k4me3_rep}.bed
#
# h3k27ac:
#   encode_meta: data/human/h3k27ac_chip/encode_metadata.tsv
#   bed_gz: data/human/h3k27ac_chip/{h3k27ac_biosamp}_{h3k27ac_rep}.bed.gz
#   bed: data/human/h3k27ac_chip/{h3k27ac_biosamp}_{h3k27ac_rep}.bed
#
# pol2:
#   encode_meta: data/human/pol2_chip/encode_metadata.tsv
#   bed_gz: data/human/pol2_chip/{pol2_biosamp}_{pol2_rep}.bed.gz
#   bed: data/human/h3k27ac_chip/{pol2_biosamp}_{pol2_rep}.bed
